/**
 * CodeBuddy native memory file with custom compaction instructions.
 *
 * CodeBuddy already compacts and caches automatically; Cretli only supplies
 * custom compaction guidance. CodeBuddy loads user memory from
 * `$HOME/.codebuddy/CODEBUDDY.md` (Cretli owns that HOME via
 * `lib/codebuddy/codebuddy-cli.js`), and its summarizer prompt tells the model
 * to follow additional summarization instructions found in the included
 * context, so a `# Compact instructions` section is the durable place for them.
 *
 * This is opt-in: nothing is written unless `codebuddyCompactInstructions` (or
 * `CRETILI_CODEBUDDY_COMPACT_INSTRUCTIONS`) is non-empty.
 *
 * The section heading follows the Claude Code convention. CodeBuddy's verified
 * native seams are the PreCompact hook stdout and `/compact [instructions]`;
 * the memory section is the declarative equivalent.
 */

import fs from 'fs';
import path from 'path';
import { loadSettings } from '../persist/settings.js';
import { ensureCodeBuddyHomeDir } from './codebuddy-cli.js';

export const CODEBUDDY_COMPACT_SECTION_HEADING = '# Compact instructions';
export const CODEBUDDY_COMPACT_INSTRUCTIONS_ENV = 'CRETILI_CODEBUDDY_COMPACT_INSTRUCTIONS';
export const CODEBUDDY_MEMORY_FILE_NAME = 'CODEBUDDY.md';
export const CODEBUDDY_MEMORY_MAX_CHARS = 20_000;

/**
 * @param {object | null} [settings]
 * @param {Record<string, string | undefined>} [env]
 * @returns {string}
 */
export function resolveCodeBuddyCompactInstructions(settings = null, env = process.env) {
  const source = env && typeof env === 'object' ? env : process.env;
  const fromEnv = String(source[CODEBUDDY_COMPACT_INSTRUCTIONS_ENV] || '').trim();
  const settingsSource = settings || loadSettings();
  const fromSettings = String(settingsSource?.codebuddyCompactInstructions || '').trim();
  const combined = fromEnv || fromSettings;
  return combined.slice(0, CODEBUDDY_MEMORY_MAX_CHARS);
}

/**
 * Build the CODEBUDDY.md body. Returns '' when there are no instructions, so a
 * caller can skip writing entirely.
 *
 * @param {{ compactInstructions?: string, intro?: string }} [input]
 * @returns {string}
 */
export function buildCodeBuddyMemoryMarkdown(input = {}) {
  const instructions = String(input.compactInstructions || '').trim();
  if (!instructions) return '';
  const intro = String(input.intro || '').trim()
    || 'Generated by Cretli. Custom guidance for CodeBuddy compaction.';
  return [
    `<!-- ${intro} -->`,
    '',
    CODEBUDDY_COMPACT_SECTION_HEADING,
    '',
    instructions,
    '',
  ].join('\n');
}

/**
 * @param {string} homeDir
 * @returns {string}
 */
export function resolveCodeBuddyMemoryPath(homeDir) {
  return path.join(
    String(homeDir || ensureCodeBuddyHomeDir()),
    '.codebuddy',
    CODEBUDDY_MEMORY_FILE_NAME,
  );
}

/**
 * Write `$HOME/.codebuddy/CODEBUDDY.md` when custom compaction instructions are
 * configured. Idempotent; returns the path and whether anything was written.
 *
 * @param {{
 *   settings?: object | null,
 *   env?: Record<string, string | undefined>,
 *   homeDir?: string,
 * }} [options]
 * @returns {{ path: string, written: boolean, markdown: string }}
 */
export function writeCodeBuddyMemoryFile(options = {}) {
  const env = options.env && typeof options.env === 'object' ? options.env : process.env;
  const homeDir = String(options.homeDir || ensureCodeBuddyHomeDir());
  const filePath = resolveCodeBuddyMemoryPath(homeDir);
  const instructions = resolveCodeBuddyCompactInstructions(options.settings ?? null, env);
  const markdown = buildCodeBuddyMemoryMarkdown({ compactInstructions: instructions });
  if (!markdown) return { path: filePath, written: false, markdown: '' };
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  let previous = '';
  try {
    previous = fs.readFileSync(filePath, 'utf8');
  } catch {
    previous = '';
  }
  if (previous === markdown) return { path: filePath, written: false, markdown };
  fs.writeFileSync(filePath, markdown, 'utf8');
  return { path: filePath, written: true, markdown };
}
