import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import './helpers/isolated-data-dir.js';
import { writeDeepSeekReviewReadOnlyPatch } from '../lib/deepseek/dsh-review-patch.js';
import { ISOLATED_DATA_DIR, removeIsolatedDataDir } from './helpers/isolated-data-dir.js';

try {
  const actualPath = writeDeepSeekReviewReadOnlyPatch();
  const expectedPath = path.join(ISOLATED_DATA_DIR, 'mcp', 'dsh-review-readonly.yml');
  assert.equal(actualPath, expectedPath);
  assert.equal(fs.existsSync(actualPath), true);
  const actualYaml = fs.readFileSync(actualPath, 'utf8');
  assert.match(actualYaml, /^# Generated by Cretli\. Do not edit\./m);
  assert.match(actualYaml, /- id: sandbox-policy/);
  assert.match(actualYaml, /mode: read-only/);
  assert.match(actualYaml, /- id: approval/);
  assert.match(actualYaml, /policy: never/);
} finally {
  removeIsolatedDataDir();
}

console.log('dsh-review-patch.test.js OK');
