import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import './helpers/isolated-data-dir.js';
import { resolveBundledDeepSeekCli } from '../lib/deepseek/deepseek-cli.js';
import { ensureDeepSeekHomeDir } from '../lib/deepseek/deepseek-home.js';
import { writeDeepSeekRuntimePatch } from '../lib/deepseek/dsh-runtime-patch.js';
import { writeDeepSeekReviewReadOnlyPatch } from '../lib/deepseek/dsh-review-patch.js';
import { ISOLATED_DATA_DIR, removeIsolatedDataDir } from './helpers/isolated-data-dir.js';

const DSH_BOOT_TIMEOUT_MS = 30000;
const PROBE_REQUEST = `${JSON.stringify({ jsonrpc: '2.0', id: 1, method: 'cretli/probe' })}\n`;

/**
 * Boots the real `dsh --profile sdk` with the given overlays; string checks on
 * the YAML cannot catch loader/schema rejections. The SDK runtime answers
 * JSON-RPC even when the plugin tree fails, so the exit status and stderr are
 * the signal.
 * @param {string} dshBin
 * @param {string[]} patches
 */
function assertDshBootsWithPatches(dshBin, patches) {
  const args = [dshBin, '--profile', 'sdk', ...patches.flatMap((patch) => ['--patch', patch])];
  const actual = spawnSync(process.execPath, args, {
    input: PROBE_REQUEST,
    encoding: 'utf8',
    timeout: DSH_BOOT_TIMEOUT_MS,
    env: { ...process.env, DSH_HOME: ensureDeepSeekHomeDir() },
  });
  assert.doesNotMatch(actual.stderr, /plugin tree failed to load/, actual.stderr);
  assert.equal(actual.status, 0, actual.stderr);
  assert.match(actual.stdout, /"jsonrpc":"2\.0","id":1/, actual.stderr);
}

try {
  const actualPath = writeDeepSeekReviewReadOnlyPatch();
  const expectedPath = path.join(ISOLATED_DATA_DIR, 'mcp', 'dsh-review-readonly.yml');
  assert.equal(actualPath, expectedPath);
  assert.equal(fs.existsSync(actualPath), true);
  const actualYaml = fs.readFileSync(actualPath, 'utf8');
  assert.match(actualYaml, /^# Generated by Cretli\. Do not edit\./m);
  assert.match(actualYaml, /- id: sandbox-policy/);
  assert.match(actualYaml, /mode: read-only/);
  assert.match(actualYaml, /workspaceRoot: !!js process\.cwd\(\)/);
  assert.match(actualYaml, /- id: approval/);
  assert.match(actualYaml, /policy: never/);
  assert.match(actualYaml, /defaultPreset: cretli-review/);
  const dshBin = resolveBundledDeepSeekCli();
  if (dshBin) {
    assertDshBootsWithPatches(dshBin, [writeDeepSeekRuntimePatch(), actualPath]);
  } else {
    console.log('dsh-review-patch.test.js: @deepseek-ai/dsh not installed, boot check skipped');
  }
} finally {
  removeIsolatedDataDir();
}

console.log('dsh-review-patch.test.js OK');
